// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/nikpopkov/running-club/api/internal/domain/model"
	mock "github.com/stretchr/testify/mock"
)

// ClubCreator is an autogenerated mock type for the clubCreator type
type ClubCreator struct {
	mock.Mock
}

type ClubCreator_Expecter struct {
	mock *mock.Mock
}

func (_m *ClubCreator) EXPECT() *ClubCreator_Expecter {
	return &ClubCreator_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, c
func (_m *ClubCreator) Create(ctx context.Context, c *model.Club) error {
	ret := _m.Called(ctx, c)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Club) error); ok {
		r0 = rf(ctx, c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ClubCreator_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type ClubCreator_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - c *model.Club
func (_e *ClubCreator_Expecter) Create(ctx interface{}, c interface{}) *ClubCreator_Create_Call {
	return &ClubCreator_Create_Call{Call: _e.mock.On("Create", ctx, c)}
}

func (_c *ClubCreator_Create_Call) Run(run func(ctx context.Context, c *model.Club)) *ClubCreator_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Club))
	})
	return _c
}

func (_c *ClubCreator_Create_Call) Return(_a0 error) *ClubCreator_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ClubCreator_Create_Call) RunAndReturn(run func(context.Context, *model.Club) error) *ClubCreator_Create_Call {
	_c.Call.Return(run)
	return _c
}

// NewClubCreator creates a new instance of ClubCreator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClubCreator(t interface {
	mock.TestingT
	Cleanup(func())
}) *ClubCreator {
	mock := &ClubCreator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
