// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	uuid "github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// ActivityRepo is an autogenerated mock type for the activityRepo type
type ActivityRepo struct {
	mock.Mock
}

type ActivityRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *ActivityRepo) EXPECT() *ActivityRepo_Expecter {
	return &ActivityRepo_Expecter{mock: &_m.Mock}
}

// SumDistByClubAthletes provides a mock function with given fields: ctx, clubID
func (_m *ActivityRepo) SumDistByClubAthletes(ctx context.Context, clubID uuid.UUID) (float64, error) {
	ret := _m.Called(ctx, clubID)

	if len(ret) == 0 {
		panic("no return value specified for SumDistByClubAthletes")
	}

	var r0 float64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (float64, error)); ok {
		return rf(ctx, clubID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) float64); ok {
		r0 = rf(ctx, clubID)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, clubID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ActivityRepo_SumDistByClubAthletes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SumDistByClubAthletes'
type ActivityRepo_SumDistByClubAthletes_Call struct {
	*mock.Call
}

// SumDistByClubAthletes is a helper method to define mock.On call
//   - ctx context.Context
//   - clubID uuid.UUID
func (_e *ActivityRepo_Expecter) SumDistByClubAthletes(ctx interface{}, clubID interface{}) *ActivityRepo_SumDistByClubAthletes_Call {
	return &ActivityRepo_SumDistByClubAthletes_Call{Call: _e.mock.On("SumDistByClubAthletes", ctx, clubID)}
}

func (_c *ActivityRepo_SumDistByClubAthletes_Call) Run(run func(ctx context.Context, clubID uuid.UUID)) *ActivityRepo_SumDistByClubAthletes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *ActivityRepo_SumDistByClubAthletes_Call) Return(_a0 float64, _a1 error) *ActivityRepo_SumDistByClubAthletes_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ActivityRepo_SumDistByClubAthletes_Call) RunAndReturn(run func(context.Context, uuid.UUID) (float64, error)) *ActivityRepo_SumDistByClubAthletes_Call {
	_c.Call.Return(run)
	return _c
}

// SumDistByUser provides a mock function with given fields: ctx, userID
func (_m *ActivityRepo) SumDistByUser(ctx context.Context, userID uuid.UUID) (float64, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for SumDistByUser")
	}

	var r0 float64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (float64, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) float64); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ActivityRepo_SumDistByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SumDistByUser'
type ActivityRepo_SumDistByUser_Call struct {
	*mock.Call
}

// SumDistByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *ActivityRepo_Expecter) SumDistByUser(ctx interface{}, userID interface{}) *ActivityRepo_SumDistByUser_Call {
	return &ActivityRepo_SumDistByUser_Call{Call: _e.mock.On("SumDistByUser", ctx, userID)}
}

func (_c *ActivityRepo_SumDistByUser_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *ActivityRepo_SumDistByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *ActivityRepo_SumDistByUser_Call) Return(_a0 float64, _a1 error) *ActivityRepo_SumDistByUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ActivityRepo_SumDistByUser_Call) RunAndReturn(run func(context.Context, uuid.UUID) (float64, error)) *ActivityRepo_SumDistByUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewActivityRepo creates a new instance of ActivityRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewActivityRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *ActivityRepo {
	mock := &ActivityRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
