// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	uuid "github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// AnnounceRepo is an autogenerated mock type for the announceRepo type
type AnnounceRepo struct {
	mock.Mock
}

type AnnounceRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *AnnounceRepo) EXPECT() *AnnounceRepo_Expecter {
	return &AnnounceRepo_Expecter{mock: &_m.Mock}
}

// AttendanceStats provides a mock function with given fields: ctx, clubID
func (_m *AnnounceRepo) AttendanceStats(ctx context.Context, clubID uuid.UUID) (int, int, error) {
	ret := _m.Called(ctx, clubID)

	if len(ret) == 0 {
		panic("no return value specified for AttendanceStats")
	}

	var r0 int
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (int, int, error)); ok {
		return rf(ctx, clubID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) int); ok {
		r0 = rf(ctx, clubID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) int); ok {
		r1 = rf(ctx, clubID)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID) error); ok {
		r2 = rf(ctx, clubID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// AnnounceRepo_AttendanceStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AttendanceStats'
type AnnounceRepo_AttendanceStats_Call struct {
	*mock.Call
}

// AttendanceStats is a helper method to define mock.On call
//   - ctx context.Context
//   - clubID uuid.UUID
func (_e *AnnounceRepo_Expecter) AttendanceStats(ctx interface{}, clubID interface{}) *AnnounceRepo_AttendanceStats_Call {
	return &AnnounceRepo_AttendanceStats_Call{Call: _e.mock.On("AttendanceStats", ctx, clubID)}
}

func (_c *AnnounceRepo_AttendanceStats_Call) Run(run func(ctx context.Context, clubID uuid.UUID)) *AnnounceRepo_AttendanceStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *AnnounceRepo_AttendanceStats_Call) Return(signedUp int, capacity int, err error) *AnnounceRepo_AttendanceStats_Call {
	_c.Call.Return(signedUp, capacity, err)
	return _c
}

func (_c *AnnounceRepo_AttendanceStats_Call) RunAndReturn(run func(context.Context, uuid.UUID) (int, int, error)) *AnnounceRepo_AttendanceStats_Call {
	_c.Call.Return(run)
	return _c
}

// NewAnnounceRepo creates a new instance of AnnounceRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAnnounceRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *AnnounceRepo {
	mock := &AnnounceRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
