// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	uuid "github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// WorkoutRepo is an autogenerated mock type for the workoutRepo type
type WorkoutRepo struct {
	mock.Mock
}

type WorkoutRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *WorkoutRepo) EXPECT() *WorkoutRepo_Expecter {
	return &WorkoutRepo_Expecter{mock: &_m.Mock}
}

// SumPlanDistByUserWeek provides a mock function with given fields: ctx, userID, weekIndex
func (_m *WorkoutRepo) SumPlanDistByUserWeek(ctx context.Context, userID uuid.UUID, weekIndex int) (float64, error) {
	ret := _m.Called(ctx, userID, weekIndex)

	if len(ret) == 0 {
		panic("no return value specified for SumPlanDistByUserWeek")
	}

	var r0 float64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int) (float64, error)); ok {
		return rf(ctx, userID, weekIndex)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int) float64); ok {
		r0 = rf(ctx, userID, weekIndex)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int) error); ok {
		r1 = rf(ctx, userID, weekIndex)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WorkoutRepo_SumPlanDistByUserWeek_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SumPlanDistByUserWeek'
type WorkoutRepo_SumPlanDistByUserWeek_Call struct {
	*mock.Call
}

// SumPlanDistByUserWeek is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - weekIndex int
func (_e *WorkoutRepo_Expecter) SumPlanDistByUserWeek(ctx interface{}, userID interface{}, weekIndex interface{}) *WorkoutRepo_SumPlanDistByUserWeek_Call {
	return &WorkoutRepo_SumPlanDistByUserWeek_Call{Call: _e.mock.On("SumPlanDistByUserWeek", ctx, userID, weekIndex)}
}

func (_c *WorkoutRepo_SumPlanDistByUserWeek_Call) Run(run func(ctx context.Context, userID uuid.UUID, weekIndex int)) *WorkoutRepo_SumPlanDistByUserWeek_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(int))
	})
	return _c
}

func (_c *WorkoutRepo_SumPlanDistByUserWeek_Call) Return(_a0 float64, _a1 error) *WorkoutRepo_SumPlanDistByUserWeek_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *WorkoutRepo_SumPlanDistByUserWeek_Call) RunAndReturn(run func(context.Context, uuid.UUID, int) (float64, error)) *WorkoutRepo_SumPlanDistByUserWeek_Call {
	_c.Call.Return(run)
	return _c
}

// NewWorkoutRepo creates a new instance of WorkoutRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWorkoutRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *WorkoutRepo {
	mock := &WorkoutRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
