// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/nikpopkov/running-club/api/internal/domain/model"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// AnnounceRepo is an autogenerated mock type for the announceRepo type
type AnnounceRepo struct {
	mock.Mock
}

type AnnounceRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *AnnounceRepo) EXPECT() *AnnounceRepo_Expecter {
	return &AnnounceRepo_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, a
func (_m *AnnounceRepo) Create(ctx context.Context, a *model.Announce) error {
	ret := _m.Called(ctx, a)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Announce) error); ok {
		r0 = rf(ctx, a)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AnnounceRepo_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type AnnounceRepo_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - a *model.Announce
func (_e *AnnounceRepo_Expecter) Create(ctx interface{}, a interface{}) *AnnounceRepo_Create_Call {
	return &AnnounceRepo_Create_Call{Call: _e.mock.On("Create", ctx, a)}
}

func (_c *AnnounceRepo_Create_Call) Run(run func(ctx context.Context, a *model.Announce)) *AnnounceRepo_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Announce))
	})
	return _c
}

func (_c *AnnounceRepo_Create_Call) Return(_a0 error) *AnnounceRepo_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AnnounceRepo_Create_Call) RunAndReturn(run func(context.Context, *model.Announce) error) *AnnounceRepo_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateSignup provides a mock function with given fields: ctx, s
func (_m *AnnounceRepo) CreateSignup(ctx context.Context, s *model.AnnounceSignup) error {
	ret := _m.Called(ctx, s)

	if len(ret) == 0 {
		panic("no return value specified for CreateSignup")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.AnnounceSignup) error); ok {
		r0 = rf(ctx, s)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AnnounceRepo_CreateSignup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSignup'
type AnnounceRepo_CreateSignup_Call struct {
	*mock.Call
}

// CreateSignup is a helper method to define mock.On call
//   - ctx context.Context
//   - s *model.AnnounceSignup
func (_e *AnnounceRepo_Expecter) CreateSignup(ctx interface{}, s interface{}) *AnnounceRepo_CreateSignup_Call {
	return &AnnounceRepo_CreateSignup_Call{Call: _e.mock.On("CreateSignup", ctx, s)}
}

func (_c *AnnounceRepo_CreateSignup_Call) Run(run func(ctx context.Context, s *model.AnnounceSignup)) *AnnounceRepo_CreateSignup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.AnnounceSignup))
	})
	return _c
}

func (_c *AnnounceRepo_CreateSignup_Call) Return(_a0 error) *AnnounceRepo_CreateSignup_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AnnounceRepo_CreateSignup_Call) RunAndReturn(run func(context.Context, *model.AnnounceSignup) error) *AnnounceRepo_CreateSignup_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSignup provides a mock function with given fields: ctx, announceID, athleteID
func (_m *AnnounceRepo) DeleteSignup(ctx context.Context, announceID uuid.UUID, athleteID uuid.UUID) error {
	ret := _m.Called(ctx, announceID, athleteID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSignup")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, announceID, athleteID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AnnounceRepo_DeleteSignup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSignup'
type AnnounceRepo_DeleteSignup_Call struct {
	*mock.Call
}

// DeleteSignup is a helper method to define mock.On call
//   - ctx context.Context
//   - announceID uuid.UUID
//   - athleteID uuid.UUID
func (_e *AnnounceRepo_Expecter) DeleteSignup(ctx interface{}, announceID interface{}, athleteID interface{}) *AnnounceRepo_DeleteSignup_Call {
	return &AnnounceRepo_DeleteSignup_Call{Call: _e.mock.On("DeleteSignup", ctx, announceID, athleteID)}
}

func (_c *AnnounceRepo_DeleteSignup_Call) Run(run func(ctx context.Context, announceID uuid.UUID, athleteID uuid.UUID)) *AnnounceRepo_DeleteSignup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *AnnounceRepo_DeleteSignup_Call) Return(_a0 error) *AnnounceRepo_DeleteSignup_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AnnounceRepo_DeleteSignup_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *AnnounceRepo_DeleteSignup_Call {
	_c.Call.Return(run)
	return _c
}

// FindByClub provides a mock function with given fields: ctx, clubID
func (_m *AnnounceRepo) FindByClub(ctx context.Context, clubID uuid.UUID) ([]*model.Announce, error) {
	ret := _m.Called(ctx, clubID)

	if len(ret) == 0 {
		panic("no return value specified for FindByClub")
	}

	var r0 []*model.Announce
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*model.Announce, error)); ok {
		return rf(ctx, clubID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*model.Announce); ok {
		r0 = rf(ctx, clubID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Announce)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, clubID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AnnounceRepo_FindByClub_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByClub'
type AnnounceRepo_FindByClub_Call struct {
	*mock.Call
}

// FindByClub is a helper method to define mock.On call
//   - ctx context.Context
//   - clubID uuid.UUID
func (_e *AnnounceRepo_Expecter) FindByClub(ctx interface{}, clubID interface{}) *AnnounceRepo_FindByClub_Call {
	return &AnnounceRepo_FindByClub_Call{Call: _e.mock.On("FindByClub", ctx, clubID)}
}

func (_c *AnnounceRepo_FindByClub_Call) Run(run func(ctx context.Context, clubID uuid.UUID)) *AnnounceRepo_FindByClub_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *AnnounceRepo_FindByClub_Call) Return(_a0 []*model.Announce, _a1 error) *AnnounceRepo_FindByClub_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AnnounceRepo_FindByClub_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]*model.Announce, error)) *AnnounceRepo_FindByClub_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *AnnounceRepo) GetByID(ctx context.Context, id uuid.UUID) (*model.Announce, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *model.Announce
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.Announce, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.Announce); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Announce)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AnnounceRepo_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type AnnounceRepo_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *AnnounceRepo_Expecter) GetByID(ctx interface{}, id interface{}) *AnnounceRepo_GetByID_Call {
	return &AnnounceRepo_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *AnnounceRepo_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *AnnounceRepo_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *AnnounceRepo_GetByID_Call) Return(_a0 *model.Announce, _a1 error) *AnnounceRepo_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AnnounceRepo_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*model.Announce, error)) *AnnounceRepo_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// HasSignup provides a mock function with given fields: ctx, announceID, athleteID
func (_m *AnnounceRepo) HasSignup(ctx context.Context, announceID uuid.UUID, athleteID uuid.UUID) (bool, error) {
	ret := _m.Called(ctx, announceID, athleteID)

	if len(ret) == 0 {
		panic("no return value specified for HasSignup")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (bool, error)); ok {
		return rf(ctx, announceID, athleteID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) bool); ok {
		r0 = rf(ctx, announceID, athleteID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, announceID, athleteID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AnnounceRepo_HasSignup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasSignup'
type AnnounceRepo_HasSignup_Call struct {
	*mock.Call
}

// HasSignup is a helper method to define mock.On call
//   - ctx context.Context
//   - announceID uuid.UUID
//   - athleteID uuid.UUID
func (_e *AnnounceRepo_Expecter) HasSignup(ctx interface{}, announceID interface{}, athleteID interface{}) *AnnounceRepo_HasSignup_Call {
	return &AnnounceRepo_HasSignup_Call{Call: _e.mock.On("HasSignup", ctx, announceID, athleteID)}
}

func (_c *AnnounceRepo_HasSignup_Call) Run(run func(ctx context.Context, announceID uuid.UUID, athleteID uuid.UUID)) *AnnounceRepo_HasSignup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *AnnounceRepo_HasSignup_Call) Return(_a0 bool, _a1 error) *AnnounceRepo_HasSignup_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AnnounceRepo_HasSignup_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (bool, error)) *AnnounceRepo_HasSignup_Call {
	_c.Call.Return(run)
	return _c
}

// IncGoing provides a mock function with given fields: ctx, id, delta
func (_m *AnnounceRepo) IncGoing(ctx context.Context, id uuid.UUID, delta int) error {
	ret := _m.Called(ctx, id, delta)

	if len(ret) == 0 {
		panic("no return value specified for IncGoing")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int) error); ok {
		r0 = rf(ctx, id, delta)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AnnounceRepo_IncGoing_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncGoing'
type AnnounceRepo_IncGoing_Call struct {
	*mock.Call
}

// IncGoing is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - delta int
func (_e *AnnounceRepo_Expecter) IncGoing(ctx interface{}, id interface{}, delta interface{}) *AnnounceRepo_IncGoing_Call {
	return &AnnounceRepo_IncGoing_Call{Call: _e.mock.On("IncGoing", ctx, id, delta)}
}

func (_c *AnnounceRepo_IncGoing_Call) Run(run func(ctx context.Context, id uuid.UUID, delta int)) *AnnounceRepo_IncGoing_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(int))
	})
	return _c
}

func (_c *AnnounceRepo_IncGoing_Call) Return(_a0 error) *AnnounceRepo_IncGoing_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AnnounceRepo_IncGoing_Call) RunAndReturn(run func(context.Context, uuid.UUID, int) error) *AnnounceRepo_IncGoing_Call {
	_c.Call.Return(run)
	return _c
}

// NewAnnounceRepo creates a new instance of AnnounceRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAnnounceRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *AnnounceRepo {
	mock := &AnnounceRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
