// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/nikpopkov/running-club/api/internal/domain/model"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// ClubResolver is an autogenerated mock type for the clubResolver type
type ClubResolver struct {
	mock.Mock
}

type ClubResolver_Expecter struct {
	mock *mock.Mock
}

func (_m *ClubResolver) EXPECT() *ClubResolver_Expecter {
	return &ClubResolver_Expecter{mock: &_m.Mock}
}

// GetByCoachID provides a mock function with given fields: ctx, coachID
func (_m *ClubResolver) GetByCoachID(ctx context.Context, coachID uuid.UUID) (*model.Club, error) {
	ret := _m.Called(ctx, coachID)

	if len(ret) == 0 {
		panic("no return value specified for GetByCoachID")
	}

	var r0 *model.Club
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.Club, error)); ok {
		return rf(ctx, coachID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.Club); ok {
		r0 = rf(ctx, coachID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Club)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, coachID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClubResolver_GetByCoachID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByCoachID'
type ClubResolver_GetByCoachID_Call struct {
	*mock.Call
}

// GetByCoachID is a helper method to define mock.On call
//   - ctx context.Context
//   - coachID uuid.UUID
func (_e *ClubResolver_Expecter) GetByCoachID(ctx interface{}, coachID interface{}) *ClubResolver_GetByCoachID_Call {
	return &ClubResolver_GetByCoachID_Call{Call: _e.mock.On("GetByCoachID", ctx, coachID)}
}

func (_c *ClubResolver_GetByCoachID_Call) Run(run func(ctx context.Context, coachID uuid.UUID)) *ClubResolver_GetByCoachID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *ClubResolver_GetByCoachID_Call) Return(_a0 *model.Club, _a1 error) *ClubResolver_GetByCoachID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ClubResolver_GetByCoachID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*model.Club, error)) *ClubResolver_GetByCoachID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *ClubResolver) GetByID(ctx context.Context, id uuid.UUID) (*model.Club, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *model.Club
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.Club, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.Club); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Club)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClubResolver_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type ClubResolver_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *ClubResolver_Expecter) GetByID(ctx interface{}, id interface{}) *ClubResolver_GetByID_Call {
	return &ClubResolver_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *ClubResolver_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *ClubResolver_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *ClubResolver_GetByID_Call) Return(_a0 *model.Club, _a1 error) *ClubResolver_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ClubResolver_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*model.Club, error)) *ClubResolver_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewClubResolver creates a new instance of ClubResolver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClubResolver(t interface {
	mock.TestingT
	Cleanup(func())
}) *ClubResolver {
	mock := &ClubResolver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
