// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/nikpopkov/running-club/api/internal/domain/model"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MembershipRepo is an autogenerated mock type for the membershipRepo type
type MembershipRepo struct {
	mock.Mock
}

type MembershipRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MembershipRepo) EXPECT() *MembershipRepo_Expecter {
	return &MembershipRepo_Expecter{mock: &_m.Mock}
}

// GetActiveByUser provides a mock function with given fields: ctx, userID
func (_m *MembershipRepo) GetActiveByUser(ctx context.Context, userID uuid.UUID) (*model.Membership, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetActiveByUser")
	}

	var r0 *model.Membership
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.Membership, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.Membership); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Membership)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MembershipRepo_GetActiveByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActiveByUser'
type MembershipRepo_GetActiveByUser_Call struct {
	*mock.Call
}

// GetActiveByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MembershipRepo_Expecter) GetActiveByUser(ctx interface{}, userID interface{}) *MembershipRepo_GetActiveByUser_Call {
	return &MembershipRepo_GetActiveByUser_Call{Call: _e.mock.On("GetActiveByUser", ctx, userID)}
}

func (_c *MembershipRepo_GetActiveByUser_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MembershipRepo_GetActiveByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MembershipRepo_GetActiveByUser_Call) Return(_a0 *model.Membership, _a1 error) *MembershipRepo_GetActiveByUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MembershipRepo_GetActiveByUser_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*model.Membership, error)) *MembershipRepo_GetActiveByUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewMembershipRepo creates a new instance of MembershipRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMembershipRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MembershipRepo {
	mock := &MembershipRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
