// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/nikpopkov/running-club/api/internal/domain/model"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// WorkoutRepo is an autogenerated mock type for the workoutRepo type
type WorkoutRepo struct {
	mock.Mock
}

type WorkoutRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *WorkoutRepo) EXPECT() *WorkoutRepo_Expecter {
	return &WorkoutRepo_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, w
func (_m *WorkoutRepo) Create(ctx context.Context, w *model.Workout) error {
	ret := _m.Called(ctx, w)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Workout) error); ok {
		r0 = rf(ctx, w)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WorkoutRepo_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type WorkoutRepo_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - w *model.Workout
func (_e *WorkoutRepo_Expecter) Create(ctx interface{}, w interface{}) *WorkoutRepo_Create_Call {
	return &WorkoutRepo_Create_Call{Call: _e.mock.On("Create", ctx, w)}
}

func (_c *WorkoutRepo_Create_Call) Run(run func(ctx context.Context, w *model.Workout)) *WorkoutRepo_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Workout))
	})
	return _c
}

func (_c *WorkoutRepo_Create_Call) Return(_a0 error) *WorkoutRepo_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *WorkoutRepo_Create_Call) RunAndReturn(run func(context.Context, *model.Workout) error) *WorkoutRepo_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByUserAndAnnounce provides a mock function with given fields: ctx, userID, announceID
func (_m *WorkoutRepo) DeleteByUserAndAnnounce(ctx context.Context, userID uuid.UUID, announceID uuid.UUID) error {
	ret := _m.Called(ctx, userID, announceID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByUserAndAnnounce")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, userID, announceID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WorkoutRepo_DeleteByUserAndAnnounce_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByUserAndAnnounce'
type WorkoutRepo_DeleteByUserAndAnnounce_Call struct {
	*mock.Call
}

// DeleteByUserAndAnnounce is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - announceID uuid.UUID
func (_e *WorkoutRepo_Expecter) DeleteByUserAndAnnounce(ctx interface{}, userID interface{}, announceID interface{}) *WorkoutRepo_DeleteByUserAndAnnounce_Call {
	return &WorkoutRepo_DeleteByUserAndAnnounce_Call{Call: _e.mock.On("DeleteByUserAndAnnounce", ctx, userID, announceID)}
}

func (_c *WorkoutRepo_DeleteByUserAndAnnounce_Call) Run(run func(ctx context.Context, userID uuid.UUID, announceID uuid.UUID)) *WorkoutRepo_DeleteByUserAndAnnounce_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *WorkoutRepo_DeleteByUserAndAnnounce_Call) Return(_a0 error) *WorkoutRepo_DeleteByUserAndAnnounce_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *WorkoutRepo_DeleteByUserAndAnnounce_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *WorkoutRepo_DeleteByUserAndAnnounce_Call {
	_c.Call.Return(run)
	return _c
}

// NewWorkoutRepo creates a new instance of WorkoutRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWorkoutRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *WorkoutRepo {
	mock := &WorkoutRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
