// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	uuid "github.com/google/uuid"
	model "github.com/nikpopkov/running-club/api/internal/domain/model"
	mock "github.com/stretchr/testify/mock"
)

// ClubRepo is an autogenerated mock type for the clubRepo type
type ClubRepo struct {
	mock.Mock
}

type ClubRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *ClubRepo) EXPECT() *ClubRepo_Expecter {
	return &ClubRepo_Expecter{mock: &_m.Mock}
}

// CountActiveStudents provides a mock function with given fields: ctx, clubID
func (_m *ClubRepo) CountActiveStudents(ctx context.Context, clubID uuid.UUID) (int, error) {
	ret := _m.Called(ctx, clubID)

	if len(ret) == 0 {
		panic("no return value specified for CountActiveStudents")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (int, error)); ok {
		return rf(ctx, clubID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) int); ok {
		r0 = rf(ctx, clubID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, clubID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClubRepo_CountActiveStudents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountActiveStudents'
type ClubRepo_CountActiveStudents_Call struct {
	*mock.Call
}

// CountActiveStudents is a helper method to define mock.On call
//   - ctx context.Context
//   - clubID uuid.UUID
func (_e *ClubRepo_Expecter) CountActiveStudents(ctx interface{}, clubID interface{}) *ClubRepo_CountActiveStudents_Call {
	return &ClubRepo_CountActiveStudents_Call{Call: _e.mock.On("CountActiveStudents", ctx, clubID)}
}

func (_c *ClubRepo_CountActiveStudents_Call) Run(run func(ctx context.Context, clubID uuid.UUID)) *ClubRepo_CountActiveStudents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *ClubRepo_CountActiveStudents_Call) Return(_a0 int, _a1 error) *ClubRepo_CountActiveStudents_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ClubRepo_CountActiveStudents_Call) RunAndReturn(run func(context.Context, uuid.UUID) (int, error)) *ClubRepo_CountActiveStudents_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, c
func (_m *ClubRepo) Create(ctx context.Context, c *model.Club) error {
	ret := _m.Called(ctx, c)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Club) error); ok {
		r0 = rf(ctx, c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ClubRepo_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type ClubRepo_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - c *model.Club
func (_e *ClubRepo_Expecter) Create(ctx interface{}, c interface{}) *ClubRepo_Create_Call {
	return &ClubRepo_Create_Call{Call: _e.mock.On("Create", ctx, c)}
}

func (_c *ClubRepo_Create_Call) Run(run func(ctx context.Context, c *model.Club)) *ClubRepo_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Club))
	})
	return _c
}

func (_c *ClubRepo_Create_Call) Return(_a0 error) *ClubRepo_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ClubRepo_Create_Call) RunAndReturn(run func(context.Context, *model.Club) error) *ClubRepo_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByCoachID provides a mock function with given fields: ctx, coachID
func (_m *ClubRepo) GetByCoachID(ctx context.Context, coachID uuid.UUID) (*model.Club, error) {
	ret := _m.Called(ctx, coachID)

	if len(ret) == 0 {
		panic("no return value specified for GetByCoachID")
	}

	var r0 *model.Club
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.Club, error)); ok {
		return rf(ctx, coachID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.Club); ok {
		r0 = rf(ctx, coachID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Club)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, coachID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClubRepo_GetByCoachID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByCoachID'
type ClubRepo_GetByCoachID_Call struct {
	*mock.Call
}

// GetByCoachID is a helper method to define mock.On call
//   - ctx context.Context
//   - coachID uuid.UUID
func (_e *ClubRepo_Expecter) GetByCoachID(ctx interface{}, coachID interface{}) *ClubRepo_GetByCoachID_Call {
	return &ClubRepo_GetByCoachID_Call{Call: _e.mock.On("GetByCoachID", ctx, coachID)}
}

func (_c *ClubRepo_GetByCoachID_Call) Run(run func(ctx context.Context, coachID uuid.UUID)) *ClubRepo_GetByCoachID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *ClubRepo_GetByCoachID_Call) Return(_a0 *model.Club, _a1 error) *ClubRepo_GetByCoachID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ClubRepo_GetByCoachID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*model.Club, error)) *ClubRepo_GetByCoachID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *ClubRepo) GetByID(ctx context.Context, id uuid.UUID) (*model.Club, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *model.Club
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.Club, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.Club); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Club)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClubRepo_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type ClubRepo_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *ClubRepo_Expecter) GetByID(ctx interface{}, id interface{}) *ClubRepo_GetByID_Call {
	return &ClubRepo_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *ClubRepo_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *ClubRepo_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *ClubRepo_GetByID_Call) Return(_a0 *model.Club, _a1 error) *ClubRepo_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ClubRepo_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*model.Club, error)) *ClubRepo_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByInviteCode provides a mock function with given fields: ctx, code
func (_m *ClubRepo) GetByInviteCode(ctx context.Context, code string) (*model.Club, error) {
	ret := _m.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for GetByInviteCode")
	}

	var r0 *model.Club
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Club, error)); ok {
		return rf(ctx, code)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Club); ok {
		r0 = rf(ctx, code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Club)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClubRepo_GetByInviteCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByInviteCode'
type ClubRepo_GetByInviteCode_Call struct {
	*mock.Call
}

// GetByInviteCode is a helper method to define mock.On call
//   - ctx context.Context
//   - code string
func (_e *ClubRepo_Expecter) GetByInviteCode(ctx interface{}, code interface{}) *ClubRepo_GetByInviteCode_Call {
	return &ClubRepo_GetByInviteCode_Call{Call: _e.mock.On("GetByInviteCode", ctx, code)}
}

func (_c *ClubRepo_GetByInviteCode_Call) Run(run func(ctx context.Context, code string)) *ClubRepo_GetByInviteCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ClubRepo_GetByInviteCode_Call) Return(_a0 *model.Club, _a1 error) *ClubRepo_GetByInviteCode_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ClubRepo_GetByInviteCode_Call) RunAndReturn(run func(context.Context, string) (*model.Club, error)) *ClubRepo_GetByInviteCode_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateAccent provides a mock function with given fields: ctx, id, accent
func (_m *ClubRepo) UpdateAccent(ctx context.Context, id uuid.UUID, accent string) error {
	ret := _m.Called(ctx, id, accent)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAccent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = rf(ctx, id, accent)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ClubRepo_UpdateAccent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateAccent'
type ClubRepo_UpdateAccent_Call struct {
	*mock.Call
}

// UpdateAccent is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - accent string
func (_e *ClubRepo_Expecter) UpdateAccent(ctx interface{}, id interface{}, accent interface{}) *ClubRepo_UpdateAccent_Call {
	return &ClubRepo_UpdateAccent_Call{Call: _e.mock.On("UpdateAccent", ctx, id, accent)}
}

func (_c *ClubRepo_UpdateAccent_Call) Run(run func(ctx context.Context, id uuid.UUID, accent string)) *ClubRepo_UpdateAccent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string))
	})
	return _c
}

func (_c *ClubRepo_UpdateAccent_Call) Return(_a0 error) *ClubRepo_UpdateAccent_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ClubRepo_UpdateAccent_Call) RunAndReturn(run func(context.Context, uuid.UUID, string) error) *ClubRepo_UpdateAccent_Call {
	_c.Call.Return(run)
	return _c
}

// NewClubRepo creates a new instance of ClubRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClubRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *ClubRepo {
	mock := &ClubRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
