// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	uuid "github.com/google/uuid"
	model "github.com/nikpopkov/running-club/api/internal/domain/model"
	mock "github.com/stretchr/testify/mock"
)

// MembershipRepo is an autogenerated mock type for the membershipRepo type
type MembershipRepo struct {
	mock.Mock
}

type MembershipRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MembershipRepo) EXPECT() *MembershipRepo_Expecter {
	return &MembershipRepo_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, m
func (_m *MembershipRepo) Create(ctx context.Context, m *model.Membership) error {
	ret := _m.Called(ctx, m)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Membership) error); ok {
		r0 = rf(ctx, m)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MembershipRepo_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MembershipRepo_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - m *model.Membership
func (_e *MembershipRepo_Expecter) Create(ctx interface{}, m interface{}) *MembershipRepo_Create_Call {
	return &MembershipRepo_Create_Call{Call: _e.mock.On("Create", ctx, m)}
}

func (_c *MembershipRepo_Create_Call) Run(run func(ctx context.Context, m *model.Membership)) *MembershipRepo_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Membership))
	})
	return _c
}

func (_c *MembershipRepo_Create_Call) Return(_a0 error) *MembershipRepo_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MembershipRepo_Create_Call) RunAndReturn(run func(context.Context, *model.Membership) error) *MembershipRepo_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetActiveByUser provides a mock function with given fields: ctx, userID
func (_m *MembershipRepo) GetActiveByUser(ctx context.Context, userID uuid.UUID) (*model.Membership, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetActiveByUser")
	}

	var r0 *model.Membership
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.Membership, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.Membership); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Membership)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MembershipRepo_GetActiveByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActiveByUser'
type MembershipRepo_GetActiveByUser_Call struct {
	*mock.Call
}

// GetActiveByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MembershipRepo_Expecter) GetActiveByUser(ctx interface{}, userID interface{}) *MembershipRepo_GetActiveByUser_Call {
	return &MembershipRepo_GetActiveByUser_Call{Call: _e.mock.On("GetActiveByUser", ctx, userID)}
}

func (_c *MembershipRepo_GetActiveByUser_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MembershipRepo_GetActiveByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MembershipRepo_GetActiveByUser_Call) Return(_a0 *model.Membership, _a1 error) *MembershipRepo_GetActiveByUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MembershipRepo_GetActiveByUser_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*model.Membership, error)) *MembershipRepo_GetActiveByUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUserAndClub provides a mock function with given fields: ctx, userID, clubID
func (_m *MembershipRepo) GetByUserAndClub(ctx context.Context, userID uuid.UUID, clubID uuid.UUID) (*model.Membership, error) {
	ret := _m.Called(ctx, userID, clubID)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserAndClub")
	}

	var r0 *model.Membership
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*model.Membership, error)); ok {
		return rf(ctx, userID, clubID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *model.Membership); ok {
		r0 = rf(ctx, userID, clubID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Membership)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, userID, clubID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MembershipRepo_GetByUserAndClub_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUserAndClub'
type MembershipRepo_GetByUserAndClub_Call struct {
	*mock.Call
}

// GetByUserAndClub is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - clubID uuid.UUID
func (_e *MembershipRepo_Expecter) GetByUserAndClub(ctx interface{}, userID interface{}, clubID interface{}) *MembershipRepo_GetByUserAndClub_Call {
	return &MembershipRepo_GetByUserAndClub_Call{Call: _e.mock.On("GetByUserAndClub", ctx, userID, clubID)}
}

func (_c *MembershipRepo_GetByUserAndClub_Call) Run(run func(ctx context.Context, userID uuid.UUID, clubID uuid.UUID)) *MembershipRepo_GetByUserAndClub_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MembershipRepo_GetByUserAndClub_Call) Return(_a0 *model.Membership, _a1 error) *MembershipRepo_GetByUserAndClub_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MembershipRepo_GetByUserAndClub_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (*model.Membership, error)) *MembershipRepo_GetByUserAndClub_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function with given fields: ctx, id, status
func (_m *MembershipRepo) UpdateStatus(ctx context.Context, id uuid.UUID, status model.MembershipStatus) error {
	ret := _m.Called(ctx, id, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.MembershipStatus) error); ok {
		r0 = rf(ctx, id, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MembershipRepo_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type MembershipRepo_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - status model.MembershipStatus
func (_e *MembershipRepo_Expecter) UpdateStatus(ctx interface{}, id interface{}, status interface{}) *MembershipRepo_UpdateStatus_Call {
	return &MembershipRepo_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", ctx, id, status)}
}

func (_c *MembershipRepo_UpdateStatus_Call) Run(run func(ctx context.Context, id uuid.UUID, status model.MembershipStatus)) *MembershipRepo_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(model.MembershipStatus))
	})
	return _c
}

func (_c *MembershipRepo_UpdateStatus_Call) Return(_a0 error) *MembershipRepo_UpdateStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MembershipRepo_UpdateStatus_Call) RunAndReturn(run func(context.Context, uuid.UUID, model.MembershipStatus) error) *MembershipRepo_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMembershipRepo creates a new instance of MembershipRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMembershipRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MembershipRepo {
	mock := &MembershipRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
