// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	uuid "github.com/google/uuid"
	model "github.com/nikpopkov/running-club/api/internal/domain/model"
	mock "github.com/stretchr/testify/mock"
)

// UserRepo is an autogenerated mock type for the userRepo type
type UserRepo struct {
	mock.Mock
}

type UserRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *UserRepo) EXPECT() *UserRepo_Expecter {
	return &UserRepo_Expecter{mock: &_m.Mock}
}

// FindAthletesByClub provides a mock function with given fields: ctx, clubID
func (_m *UserRepo) FindAthletesByClub(ctx context.Context, clubID uuid.UUID) ([]*model.User, error) {
	ret := _m.Called(ctx, clubID)

	if len(ret) == 0 {
		panic("no return value specified for FindAthletesByClub")
	}

	var r0 []*model.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*model.User, error)); ok {
		return rf(ctx, clubID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*model.User); ok {
		r0 = rf(ctx, clubID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, clubID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRepo_FindAthletesByClub_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAthletesByClub'
type UserRepo_FindAthletesByClub_Call struct {
	*mock.Call
}

// FindAthletesByClub is a helper method to define mock.On call
//   - ctx context.Context
//   - clubID uuid.UUID
func (_e *UserRepo_Expecter) FindAthletesByClub(ctx interface{}, clubID interface{}) *UserRepo_FindAthletesByClub_Call {
	return &UserRepo_FindAthletesByClub_Call{Call: _e.mock.On("FindAthletesByClub", ctx, clubID)}
}

func (_c *UserRepo_FindAthletesByClub_Call) Run(run func(ctx context.Context, clubID uuid.UUID)) *UserRepo_FindAthletesByClub_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *UserRepo_FindAthletesByClub_Call) Return(_a0 []*model.User, _a1 error) *UserRepo_FindAthletesByClub_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserRepo_FindAthletesByClub_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]*model.User, error)) *UserRepo_FindAthletesByClub_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *UserRepo) GetByID(ctx context.Context, id uuid.UUID) (*model.User, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *model.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.User, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.User); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRepo_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type UserRepo_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *UserRepo_Expecter) GetByID(ctx interface{}, id interface{}) *UserRepo_GetByID_Call {
	return &UserRepo_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *UserRepo_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *UserRepo_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *UserRepo_GetByID_Call) Return(_a0 *model.User, _a1 error) *UserRepo_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserRepo_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*model.User, error)) *UserRepo_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewUserRepo creates a new instance of UserRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserRepo {
	mock := &UserRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
