// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/nikpopkov/running-club/api/internal/domain/model"
	mock "github.com/stretchr/testify/mock"

	time "time"

	uuid "github.com/google/uuid"
)

// ActivityRepo is an autogenerated mock type for the activityRepo type
type ActivityRepo struct {
	mock.Mock
}

type ActivityRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *ActivityRepo) EXPECT() *ActivityRepo_Expecter {
	return &ActivityRepo_Expecter{mock: &_m.Mock}
}

// FindByUser provides a mock function with given fields: ctx, userID
func (_m *ActivityRepo) FindByUser(ctx context.Context, userID uuid.UUID) ([]*model.Activity, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindByUser")
	}

	var r0 []*model.Activity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*model.Activity, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*model.Activity); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Activity)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ActivityRepo_FindByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByUser'
type ActivityRepo_FindByUser_Call struct {
	*mock.Call
}

// FindByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *ActivityRepo_Expecter) FindByUser(ctx interface{}, userID interface{}) *ActivityRepo_FindByUser_Call {
	return &ActivityRepo_FindByUser_Call{Call: _e.mock.On("FindByUser", ctx, userID)}
}

func (_c *ActivityRepo_FindByUser_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *ActivityRepo_FindByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *ActivityRepo_FindByUser_Call) Return(_a0 []*model.Activity, _a1 error) *ActivityRepo_FindByUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ActivityRepo_FindByUser_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]*model.Activity, error)) *ActivityRepo_FindByUser_Call {
	_c.Call.Return(run)
	return _c
}

// SumDistByUserSince provides a mock function with given fields: ctx, userID, since
func (_m *ActivityRepo) SumDistByUserSince(ctx context.Context, userID uuid.UUID, since time.Time) (float64, error) {
	ret := _m.Called(ctx, userID, since)

	if len(ret) == 0 {
		panic("no return value specified for SumDistByUserSince")
	}

	var r0 float64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) (float64, error)); ok {
		return rf(ctx, userID, since)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) float64); ok {
		r0 = rf(ctx, userID, since)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, time.Time) error); ok {
		r1 = rf(ctx, userID, since)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ActivityRepo_SumDistByUserSince_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SumDistByUserSince'
type ActivityRepo_SumDistByUserSince_Call struct {
	*mock.Call
}

// SumDistByUserSince is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - since time.Time
func (_e *ActivityRepo_Expecter) SumDistByUserSince(ctx interface{}, userID interface{}, since interface{}) *ActivityRepo_SumDistByUserSince_Call {
	return &ActivityRepo_SumDistByUserSince_Call{Call: _e.mock.On("SumDistByUserSince", ctx, userID, since)}
}

func (_c *ActivityRepo_SumDistByUserSince_Call) Run(run func(ctx context.Context, userID uuid.UUID, since time.Time)) *ActivityRepo_SumDistByUserSince_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(time.Time))
	})
	return _c
}

func (_c *ActivityRepo_SumDistByUserSince_Call) Return(_a0 float64, _a1 error) *ActivityRepo_SumDistByUserSince_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ActivityRepo_SumDistByUserSince_Call) RunAndReturn(run func(context.Context, uuid.UUID, time.Time) (float64, error)) *ActivityRepo_SumDistByUserSince_Call {
	_c.Call.Return(run)
	return _c
}

// NewActivityRepo creates a new instance of ActivityRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewActivityRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *ActivityRepo {
	mock := &ActivityRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
