// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// AnnounceRepo is an autogenerated mock type for the announceRepo type
type AnnounceRepo struct {
	mock.Mock
}

type AnnounceRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *AnnounceRepo) EXPECT() *AnnounceRepo_Expecter {
	return &AnnounceRepo_Expecter{mock: &_m.Mock}
}

// NextLabelForAthlete provides a mock function with given fields: ctx, clubID, athleteID
func (_m *AnnounceRepo) NextLabelForAthlete(ctx context.Context, clubID uuid.UUID, athleteID uuid.UUID) (string, error) {
	ret := _m.Called(ctx, clubID, athleteID)

	if len(ret) == 0 {
		panic("no return value specified for NextLabelForAthlete")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (string, error)); ok {
		return rf(ctx, clubID, athleteID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) string); ok {
		r0 = rf(ctx, clubID, athleteID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, clubID, athleteID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AnnounceRepo_NextLabelForAthlete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NextLabelForAthlete'
type AnnounceRepo_NextLabelForAthlete_Call struct {
	*mock.Call
}

// NextLabelForAthlete is a helper method to define mock.On call
//   - ctx context.Context
//   - clubID uuid.UUID
//   - athleteID uuid.UUID
func (_e *AnnounceRepo_Expecter) NextLabelForAthlete(ctx interface{}, clubID interface{}, athleteID interface{}) *AnnounceRepo_NextLabelForAthlete_Call {
	return &AnnounceRepo_NextLabelForAthlete_Call{Call: _e.mock.On("NextLabelForAthlete", ctx, clubID, athleteID)}
}

func (_c *AnnounceRepo_NextLabelForAthlete_Call) Run(run func(ctx context.Context, clubID uuid.UUID, athleteID uuid.UUID)) *AnnounceRepo_NextLabelForAthlete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *AnnounceRepo_NextLabelForAthlete_Call) Return(_a0 string, _a1 error) *AnnounceRepo_NextLabelForAthlete_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AnnounceRepo_NextLabelForAthlete_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (string, error)) *AnnounceRepo_NextLabelForAthlete_Call {
	_c.Call.Return(run)
	return _c
}

// NewAnnounceRepo creates a new instance of AnnounceRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAnnounceRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *AnnounceRepo {
	mock := &AnnounceRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
