// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/nikpopkov/running-club/api/internal/domain/model"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// PlanWeekRepo is an autogenerated mock type for the planWeekRepo type
type PlanWeekRepo struct {
	mock.Mock
}

type PlanWeekRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *PlanWeekRepo) EXPECT() *PlanWeekRepo_Expecter {
	return &PlanWeekRepo_Expecter{mock: &_m.Mock}
}

// GetByClubAndIndex provides a mock function with given fields: ctx, clubID, weekIndex
func (_m *PlanWeekRepo) GetByClubAndIndex(ctx context.Context, clubID uuid.UUID, weekIndex int) (*model.PlanWeek, error) {
	ret := _m.Called(ctx, clubID, weekIndex)

	if len(ret) == 0 {
		panic("no return value specified for GetByClubAndIndex")
	}

	var r0 *model.PlanWeek
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int) (*model.PlanWeek, error)); ok {
		return rf(ctx, clubID, weekIndex)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int) *model.PlanWeek); ok {
		r0 = rf(ctx, clubID, weekIndex)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.PlanWeek)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int) error); ok {
		r1 = rf(ctx, clubID, weekIndex)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PlanWeekRepo_GetByClubAndIndex_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByClubAndIndex'
type PlanWeekRepo_GetByClubAndIndex_Call struct {
	*mock.Call
}

// GetByClubAndIndex is a helper method to define mock.On call
//   - ctx context.Context
//   - clubID uuid.UUID
//   - weekIndex int
func (_e *PlanWeekRepo_Expecter) GetByClubAndIndex(ctx interface{}, clubID interface{}, weekIndex interface{}) *PlanWeekRepo_GetByClubAndIndex_Call {
	return &PlanWeekRepo_GetByClubAndIndex_Call{Call: _e.mock.On("GetByClubAndIndex", ctx, clubID, weekIndex)}
}

func (_c *PlanWeekRepo_GetByClubAndIndex_Call) Run(run func(ctx context.Context, clubID uuid.UUID, weekIndex int)) *PlanWeekRepo_GetByClubAndIndex_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(int))
	})
	return _c
}

func (_c *PlanWeekRepo_GetByClubAndIndex_Call) Return(_a0 *model.PlanWeek, _a1 error) *PlanWeekRepo_GetByClubAndIndex_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PlanWeekRepo_GetByClubAndIndex_Call) RunAndReturn(run func(context.Context, uuid.UUID, int) (*model.PlanWeek, error)) *PlanWeekRepo_GetByClubAndIndex_Call {
	_c.Call.Return(run)
	return _c
}

// NewPlanWeekRepo creates a new instance of PlanWeekRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPlanWeekRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *PlanWeekRepo {
	mock := &PlanWeekRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
