// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/nikpopkov/running-club/api/internal/domain/model"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// WorkoutRepo is an autogenerated mock type for the workoutRepo type
type WorkoutRepo struct {
	mock.Mock
}

type WorkoutRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *WorkoutRepo) EXPECT() *WorkoutRepo_Expecter {
	return &WorkoutRepo_Expecter{mock: &_m.Mock}
}

// FindByUser provides a mock function with given fields: ctx, userID
func (_m *WorkoutRepo) FindByUser(ctx context.Context, userID uuid.UUID) ([]*model.Workout, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindByUser")
	}

	var r0 []*model.Workout
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*model.Workout, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*model.Workout); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Workout)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WorkoutRepo_FindByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByUser'
type WorkoutRepo_FindByUser_Call struct {
	*mock.Call
}

// FindByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *WorkoutRepo_Expecter) FindByUser(ctx interface{}, userID interface{}) *WorkoutRepo_FindByUser_Call {
	return &WorkoutRepo_FindByUser_Call{Call: _e.mock.On("FindByUser", ctx, userID)}
}

func (_c *WorkoutRepo_FindByUser_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *WorkoutRepo_FindByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *WorkoutRepo_FindByUser_Call) Return(_a0 []*model.Workout, _a1 error) *WorkoutRepo_FindByUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *WorkoutRepo_FindByUser_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]*model.Workout, error)) *WorkoutRepo_FindByUser_Call {
	_c.Call.Return(run)
	return _c
}

// FindByUserWeek provides a mock function with given fields: ctx, userID, week, kind
func (_m *WorkoutRepo) FindByUserWeek(ctx context.Context, userID uuid.UUID, week int, kind model.WorkoutKind) ([]*model.Workout, error) {
	ret := _m.Called(ctx, userID, week, kind)

	if len(ret) == 0 {
		panic("no return value specified for FindByUserWeek")
	}

	var r0 []*model.Workout
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, model.WorkoutKind) ([]*model.Workout, error)); ok {
		return rf(ctx, userID, week, kind)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, model.WorkoutKind) []*model.Workout); ok {
		r0 = rf(ctx, userID, week, kind)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Workout)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int, model.WorkoutKind) error); ok {
		r1 = rf(ctx, userID, week, kind)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WorkoutRepo_FindByUserWeek_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByUserWeek'
type WorkoutRepo_FindByUserWeek_Call struct {
	*mock.Call
}

// FindByUserWeek is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - week int
//   - kind model.WorkoutKind
func (_e *WorkoutRepo_Expecter) FindByUserWeek(ctx interface{}, userID interface{}, week interface{}, kind interface{}) *WorkoutRepo_FindByUserWeek_Call {
	return &WorkoutRepo_FindByUserWeek_Call{Call: _e.mock.On("FindByUserWeek", ctx, userID, week, kind)}
}

func (_c *WorkoutRepo_FindByUserWeek_Call) Run(run func(ctx context.Context, userID uuid.UUID, week int, kind model.WorkoutKind)) *WorkoutRepo_FindByUserWeek_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(int), args[3].(model.WorkoutKind))
	})
	return _c
}

func (_c *WorkoutRepo_FindByUserWeek_Call) Return(_a0 []*model.Workout, _a1 error) *WorkoutRepo_FindByUserWeek_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *WorkoutRepo_FindByUserWeek_Call) RunAndReturn(run func(context.Context, uuid.UUID, int, model.WorkoutKind) ([]*model.Workout, error)) *WorkoutRepo_FindByUserWeek_Call {
	_c.Call.Return(run)
	return _c
}

// SumPlanDistByUserWeek provides a mock function with given fields: ctx, userID, weekIndex
func (_m *WorkoutRepo) SumPlanDistByUserWeek(ctx context.Context, userID uuid.UUID, weekIndex int) (float64, error) {
	ret := _m.Called(ctx, userID, weekIndex)

	if len(ret) == 0 {
		panic("no return value specified for SumPlanDistByUserWeek")
	}

	var r0 float64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int) (float64, error)); ok {
		return rf(ctx, userID, weekIndex)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int) float64); ok {
		r0 = rf(ctx, userID, weekIndex)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int) error); ok {
		r1 = rf(ctx, userID, weekIndex)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WorkoutRepo_SumPlanDistByUserWeek_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SumPlanDistByUserWeek'
type WorkoutRepo_SumPlanDistByUserWeek_Call struct {
	*mock.Call
}

// SumPlanDistByUserWeek is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - weekIndex int
func (_e *WorkoutRepo_Expecter) SumPlanDistByUserWeek(ctx interface{}, userID interface{}, weekIndex interface{}) *WorkoutRepo_SumPlanDistByUserWeek_Call {
	return &WorkoutRepo_SumPlanDistByUserWeek_Call{Call: _e.mock.On("SumPlanDistByUserWeek", ctx, userID, weekIndex)}
}

func (_c *WorkoutRepo_SumPlanDistByUserWeek_Call) Run(run func(ctx context.Context, userID uuid.UUID, weekIndex int)) *WorkoutRepo_SumPlanDistByUserWeek_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(int))
	})
	return _c
}

func (_c *WorkoutRepo_SumPlanDistByUserWeek_Call) Return(_a0 float64, _a1 error) *WorkoutRepo_SumPlanDistByUserWeek_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *WorkoutRepo_SumPlanDistByUserWeek_Call) RunAndReturn(run func(context.Context, uuid.UUID, int) (float64, error)) *WorkoutRepo_SumPlanDistByUserWeek_Call {
	_c.Call.Return(run)
	return _c
}

// NewWorkoutRepo creates a new instance of WorkoutRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWorkoutRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *WorkoutRepo {
	mock := &WorkoutRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
