// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/nikpopkov/running-club/api/internal/domain/model"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// WorkoutRepo is an autogenerated mock type for the workoutRepo type
type WorkoutRepo struct {
	mock.Mock
}

type WorkoutRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *WorkoutRepo) EXPECT() *WorkoutRepo_Expecter {
	return &WorkoutRepo_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, w
func (_m *WorkoutRepo) Create(ctx context.Context, w *model.Workout) error {
	ret := _m.Called(ctx, w)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Workout) error); ok {
		r0 = rf(ctx, w)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WorkoutRepo_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type WorkoutRepo_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - w *model.Workout
func (_e *WorkoutRepo_Expecter) Create(ctx interface{}, w interface{}) *WorkoutRepo_Create_Call {
	return &WorkoutRepo_Create_Call{Call: _e.mock.On("Create", ctx, w)}
}

func (_c *WorkoutRepo_Create_Call) Run(run func(ctx context.Context, w *model.Workout)) *WorkoutRepo_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Workout))
	})
	return _c
}

func (_c *WorkoutRepo_Create_Call) Return(_a0 error) *WorkoutRepo_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *WorkoutRepo_Create_Call) RunAndReturn(run func(context.Context, *model.Workout) error) *WorkoutRepo_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteClubAssignedPlans provides a mock function with given fields: ctx, userID, weekIndex
func (_m *WorkoutRepo) DeleteClubAssignedPlans(ctx context.Context, userID uuid.UUID, weekIndex int) error {
	ret := _m.Called(ctx, userID, weekIndex)

	if len(ret) == 0 {
		panic("no return value specified for DeleteClubAssignedPlans")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int) error); ok {
		r0 = rf(ctx, userID, weekIndex)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WorkoutRepo_DeleteClubAssignedPlans_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteClubAssignedPlans'
type WorkoutRepo_DeleteClubAssignedPlans_Call struct {
	*mock.Call
}

// DeleteClubAssignedPlans is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - weekIndex int
func (_e *WorkoutRepo_Expecter) DeleteClubAssignedPlans(ctx interface{}, userID interface{}, weekIndex interface{}) *WorkoutRepo_DeleteClubAssignedPlans_Call {
	return &WorkoutRepo_DeleteClubAssignedPlans_Call{Call: _e.mock.On("DeleteClubAssignedPlans", ctx, userID, weekIndex)}
}

func (_c *WorkoutRepo_DeleteClubAssignedPlans_Call) Run(run func(ctx context.Context, userID uuid.UUID, weekIndex int)) *WorkoutRepo_DeleteClubAssignedPlans_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(int))
	})
	return _c
}

func (_c *WorkoutRepo_DeleteClubAssignedPlans_Call) Return(_a0 error) *WorkoutRepo_DeleteClubAssignedPlans_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *WorkoutRepo_DeleteClubAssignedPlans_Call) RunAndReturn(run func(context.Context, uuid.UUID, int) error) *WorkoutRepo_DeleteClubAssignedPlans_Call {
	_c.Call.Return(run)
	return _c
}

// FindClubTemplates provides a mock function with given fields: ctx, clubID, weekIndex
func (_m *WorkoutRepo) FindClubTemplates(ctx context.Context, clubID uuid.UUID, weekIndex int) ([]*model.Workout, error) {
	ret := _m.Called(ctx, clubID, weekIndex)

	if len(ret) == 0 {
		panic("no return value specified for FindClubTemplates")
	}

	var r0 []*model.Workout
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int) ([]*model.Workout, error)); ok {
		return rf(ctx, clubID, weekIndex)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int) []*model.Workout); ok {
		r0 = rf(ctx, clubID, weekIndex)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Workout)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int) error); ok {
		r1 = rf(ctx, clubID, weekIndex)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WorkoutRepo_FindClubTemplates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindClubTemplates'
type WorkoutRepo_FindClubTemplates_Call struct {
	*mock.Call
}

// FindClubTemplates is a helper method to define mock.On call
//   - ctx context.Context
//   - clubID uuid.UUID
//   - weekIndex int
func (_e *WorkoutRepo_Expecter) FindClubTemplates(ctx interface{}, clubID interface{}, weekIndex interface{}) *WorkoutRepo_FindClubTemplates_Call {
	return &WorkoutRepo_FindClubTemplates_Call{Call: _e.mock.On("FindClubTemplates", ctx, clubID, weekIndex)}
}

func (_c *WorkoutRepo_FindClubTemplates_Call) Run(run func(ctx context.Context, clubID uuid.UUID, weekIndex int)) *WorkoutRepo_FindClubTemplates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(int))
	})
	return _c
}

func (_c *WorkoutRepo_FindClubTemplates_Call) Return(_a0 []*model.Workout, _a1 error) *WorkoutRepo_FindClubTemplates_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *WorkoutRepo_FindClubTemplates_Call) RunAndReturn(run func(context.Context, uuid.UUID, int) ([]*model.Workout, error)) *WorkoutRepo_FindClubTemplates_Call {
	_c.Call.Return(run)
	return _c
}

// ReplaceClubTemplates provides a mock function with given fields: ctx, clubID, weekIndex, workouts
func (_m *WorkoutRepo) ReplaceClubTemplates(ctx context.Context, clubID uuid.UUID, weekIndex int, workouts []*model.Workout) error {
	ret := _m.Called(ctx, clubID, weekIndex, workouts)

	if len(ret) == 0 {
		panic("no return value specified for ReplaceClubTemplates")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, []*model.Workout) error); ok {
		r0 = rf(ctx, clubID, weekIndex, workouts)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WorkoutRepo_ReplaceClubTemplates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReplaceClubTemplates'
type WorkoutRepo_ReplaceClubTemplates_Call struct {
	*mock.Call
}

// ReplaceClubTemplates is a helper method to define mock.On call
//   - ctx context.Context
//   - clubID uuid.UUID
//   - weekIndex int
//   - workouts []*model.Workout
func (_e *WorkoutRepo_Expecter) ReplaceClubTemplates(ctx interface{}, clubID interface{}, weekIndex interface{}, workouts interface{}) *WorkoutRepo_ReplaceClubTemplates_Call {
	return &WorkoutRepo_ReplaceClubTemplates_Call{Call: _e.mock.On("ReplaceClubTemplates", ctx, clubID, weekIndex, workouts)}
}

func (_c *WorkoutRepo_ReplaceClubTemplates_Call) Run(run func(ctx context.Context, clubID uuid.UUID, weekIndex int, workouts []*model.Workout)) *WorkoutRepo_ReplaceClubTemplates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(int), args[3].([]*model.Workout))
	})
	return _c
}

func (_c *WorkoutRepo_ReplaceClubTemplates_Call) Return(_a0 error) *WorkoutRepo_ReplaceClubTemplates_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *WorkoutRepo_ReplaceClubTemplates_Call) RunAndReturn(run func(context.Context, uuid.UUID, int, []*model.Workout) error) *WorkoutRepo_ReplaceClubTemplates_Call {
	_c.Call.Return(run)
	return _c
}

// NewWorkoutRepo creates a new instance of WorkoutRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWorkoutRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *WorkoutRepo {
	mock := &WorkoutRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
