// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/nikpopkov/running-club/api/internal/domain/model"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// ActivityRepo is an autogenerated mock type for the activityRepo type
type ActivityRepo struct {
	mock.Mock
}

type ActivityRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *ActivityRepo) EXPECT() *ActivityRepo_Expecter {
	return &ActivityRepo_Expecter{mock: &_m.Mock}
}

// DeleteByUserSourceExternalID provides a mock function with given fields: ctx, userID, source, externalID
func (_m *ActivityRepo) DeleteByUserSourceExternalID(ctx context.Context, userID uuid.UUID, source string, externalID string) error {
	ret := _m.Called(ctx, userID, source, externalID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByUserSourceExternalID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string) error); ok {
		r0 = rf(ctx, userID, source, externalID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ActivityRepo_DeleteByUserSourceExternalID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByUserSourceExternalID'
type ActivityRepo_DeleteByUserSourceExternalID_Call struct {
	*mock.Call
}

// DeleteByUserSourceExternalID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - source string
//   - externalID string
func (_e *ActivityRepo_Expecter) DeleteByUserSourceExternalID(ctx interface{}, userID interface{}, source interface{}, externalID interface{}) *ActivityRepo_DeleteByUserSourceExternalID_Call {
	return &ActivityRepo_DeleteByUserSourceExternalID_Call{Call: _e.mock.On("DeleteByUserSourceExternalID", ctx, userID, source, externalID)}
}

func (_c *ActivityRepo_DeleteByUserSourceExternalID_Call) Run(run func(ctx context.Context, userID uuid.UUID, source string, externalID string)) *ActivityRepo_DeleteByUserSourceExternalID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *ActivityRepo_DeleteByUserSourceExternalID_Call) Return(_a0 error) *ActivityRepo_DeleteByUserSourceExternalID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ActivityRepo_DeleteByUserSourceExternalID_Call) RunAndReturn(run func(context.Context, uuid.UUID, string, string) error) *ActivityRepo_DeleteByUserSourceExternalID_Call {
	_c.Call.Return(run)
	return _c
}

// Upsert provides a mock function with given fields: ctx, activity
func (_m *ActivityRepo) Upsert(ctx context.Context, activity *model.Activity) error {
	ret := _m.Called(ctx, activity)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Activity) error); ok {
		r0 = rf(ctx, activity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ActivityRepo_Upsert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upsert'
type ActivityRepo_Upsert_Call struct {
	*mock.Call
}

// Upsert is a helper method to define mock.On call
//   - ctx context.Context
//   - activity *model.Activity
func (_e *ActivityRepo_Expecter) Upsert(ctx interface{}, activity interface{}) *ActivityRepo_Upsert_Call {
	return &ActivityRepo_Upsert_Call{Call: _e.mock.On("Upsert", ctx, activity)}
}

func (_c *ActivityRepo_Upsert_Call) Run(run func(ctx context.Context, activity *model.Activity)) *ActivityRepo_Upsert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Activity))
	})
	return _c
}

func (_c *ActivityRepo_Upsert_Call) Return(_a0 error) *ActivityRepo_Upsert_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ActivityRepo_Upsert_Call) RunAndReturn(run func(context.Context, *model.Activity) error) *ActivityRepo_Upsert_Call {
	_c.Call.Return(run)
	return _c
}

// NewActivityRepo creates a new instance of ActivityRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewActivityRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *ActivityRepo {
	mock := &ActivityRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
