// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/nikpopkov/running-club/api/internal/domain/model"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// ActivityStreamRepo is an autogenerated mock type for the activityStreamRepo type
type ActivityStreamRepo struct {
	mock.Mock
}

type ActivityStreamRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *ActivityStreamRepo) EXPECT() *ActivityStreamRepo_Expecter {
	return &ActivityStreamRepo_Expecter{mock: &_m.Mock}
}

// ReplaceByActivityID provides a mock function with given fields: ctx, activityID, streams
func (_m *ActivityStreamRepo) ReplaceByActivityID(ctx context.Context, activityID uuid.UUID, streams []*model.ActivityStream) error {
	ret := _m.Called(ctx, activityID, streams)

	if len(ret) == 0 {
		panic("no return value specified for ReplaceByActivityID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, []*model.ActivityStream) error); ok {
		r0 = rf(ctx, activityID, streams)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ActivityStreamRepo_ReplaceByActivityID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReplaceByActivityID'
type ActivityStreamRepo_ReplaceByActivityID_Call struct {
	*mock.Call
}

// ReplaceByActivityID is a helper method to define mock.On call
//   - ctx context.Context
//   - activityID uuid.UUID
//   - streams []*model.ActivityStream
func (_e *ActivityStreamRepo_Expecter) ReplaceByActivityID(ctx interface{}, activityID interface{}, streams interface{}) *ActivityStreamRepo_ReplaceByActivityID_Call {
	return &ActivityStreamRepo_ReplaceByActivityID_Call{Call: _e.mock.On("ReplaceByActivityID", ctx, activityID, streams)}
}

func (_c *ActivityStreamRepo_ReplaceByActivityID_Call) Run(run func(ctx context.Context, activityID uuid.UUID, streams []*model.ActivityStream)) *ActivityStreamRepo_ReplaceByActivityID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].([]*model.ActivityStream))
	})
	return _c
}

func (_c *ActivityStreamRepo_ReplaceByActivityID_Call) Return(_a0 error) *ActivityStreamRepo_ReplaceByActivityID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ActivityStreamRepo_ReplaceByActivityID_Call) RunAndReturn(run func(context.Context, uuid.UUID, []*model.ActivityStream) error) *ActivityStreamRepo_ReplaceByActivityID_Call {
	_c.Call.Return(run)
	return _c
}

// NewActivityStreamRepo creates a new instance of ActivityStreamRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewActivityStreamRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *ActivityStreamRepo {
	mock := &ActivityStreamRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
