// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/nikpopkov/running-club/api/internal/domain/model"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// IntegrationRepo is an autogenerated mock type for the integrationRepo type
type IntegrationRepo struct {
	mock.Mock
}

type IntegrationRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *IntegrationRepo) EXPECT() *IntegrationRepo_Expecter {
	return &IntegrationRepo_Expecter{mock: &_m.Mock}
}

// GetByProviderExternalAthleteID provides a mock function with given fields: ctx, provider, externalAthleteID
func (_m *IntegrationRepo) GetByProviderExternalAthleteID(ctx context.Context, provider model.IntegrationProvider, externalAthleteID string) (*model.UserIntegration, error) {
	ret := _m.Called(ctx, provider, externalAthleteID)

	if len(ret) == 0 {
		panic("no return value specified for GetByProviderExternalAthleteID")
	}

	var r0 *model.UserIntegration
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.IntegrationProvider, string) (*model.UserIntegration, error)); ok {
		return rf(ctx, provider, externalAthleteID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.IntegrationProvider, string) *model.UserIntegration); ok {
		r0 = rf(ctx, provider, externalAthleteID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserIntegration)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.IntegrationProvider, string) error); ok {
		r1 = rf(ctx, provider, externalAthleteID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IntegrationRepo_GetByProviderExternalAthleteID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByProviderExternalAthleteID'
type IntegrationRepo_GetByProviderExternalAthleteID_Call struct {
	*mock.Call
}

// GetByProviderExternalAthleteID is a helper method to define mock.On call
//   - ctx context.Context
//   - provider model.IntegrationProvider
//   - externalAthleteID string
func (_e *IntegrationRepo_Expecter) GetByProviderExternalAthleteID(ctx interface{}, provider interface{}, externalAthleteID interface{}) *IntegrationRepo_GetByProviderExternalAthleteID_Call {
	return &IntegrationRepo_GetByProviderExternalAthleteID_Call{Call: _e.mock.On("GetByProviderExternalAthleteID", ctx, provider, externalAthleteID)}
}

func (_c *IntegrationRepo_GetByProviderExternalAthleteID_Call) Run(run func(ctx context.Context, provider model.IntegrationProvider, externalAthleteID string)) *IntegrationRepo_GetByProviderExternalAthleteID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.IntegrationProvider), args[2].(string))
	})
	return _c
}

func (_c *IntegrationRepo_GetByProviderExternalAthleteID_Call) Return(_a0 *model.UserIntegration, _a1 error) *IntegrationRepo_GetByProviderExternalAthleteID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IntegrationRepo_GetByProviderExternalAthleteID_Call) RunAndReturn(run func(context.Context, model.IntegrationProvider, string) (*model.UserIntegration, error)) *IntegrationRepo_GetByProviderExternalAthleteID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUserProvider provides a mock function with given fields: ctx, userID, provider
func (_m *IntegrationRepo) GetByUserProvider(ctx context.Context, userID uuid.UUID, provider model.IntegrationProvider) (*model.UserIntegration, error) {
	ret := _m.Called(ctx, userID, provider)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserProvider")
	}

	var r0 *model.UserIntegration
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.IntegrationProvider) (*model.UserIntegration, error)); ok {
		return rf(ctx, userID, provider)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.IntegrationProvider) *model.UserIntegration); ok {
		r0 = rf(ctx, userID, provider)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserIntegration)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, model.IntegrationProvider) error); ok {
		r1 = rf(ctx, userID, provider)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IntegrationRepo_GetByUserProvider_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUserProvider'
type IntegrationRepo_GetByUserProvider_Call struct {
	*mock.Call
}

// GetByUserProvider is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - provider model.IntegrationProvider
func (_e *IntegrationRepo_Expecter) GetByUserProvider(ctx interface{}, userID interface{}, provider interface{}) *IntegrationRepo_GetByUserProvider_Call {
	return &IntegrationRepo_GetByUserProvider_Call{Call: _e.mock.On("GetByUserProvider", ctx, userID, provider)}
}

func (_c *IntegrationRepo_GetByUserProvider_Call) Run(run func(ctx context.Context, userID uuid.UUID, provider model.IntegrationProvider)) *IntegrationRepo_GetByUserProvider_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(model.IntegrationProvider))
	})
	return _c
}

func (_c *IntegrationRepo_GetByUserProvider_Call) Return(_a0 *model.UserIntegration, _a1 error) *IntegrationRepo_GetByUserProvider_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IntegrationRepo_GetByUserProvider_Call) RunAndReturn(run func(context.Context, uuid.UUID, model.IntegrationProvider) (*model.UserIntegration, error)) *IntegrationRepo_GetByUserProvider_Call {
	_c.Call.Return(run)
	return _c
}

// Upsert provides a mock function with given fields: ctx, integration
func (_m *IntegrationRepo) Upsert(ctx context.Context, integration *model.UserIntegration) error {
	ret := _m.Called(ctx, integration)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.UserIntegration) error); ok {
		r0 = rf(ctx, integration)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IntegrationRepo_Upsert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upsert'
type IntegrationRepo_Upsert_Call struct {
	*mock.Call
}

// Upsert is a helper method to define mock.On call
//   - ctx context.Context
//   - integration *model.UserIntegration
func (_e *IntegrationRepo_Expecter) Upsert(ctx interface{}, integration interface{}) *IntegrationRepo_Upsert_Call {
	return &IntegrationRepo_Upsert_Call{Call: _e.mock.On("Upsert", ctx, integration)}
}

func (_c *IntegrationRepo_Upsert_Call) Run(run func(ctx context.Context, integration *model.UserIntegration)) *IntegrationRepo_Upsert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.UserIntegration))
	})
	return _c
}

func (_c *IntegrationRepo_Upsert_Call) Return(_a0 error) *IntegrationRepo_Upsert_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IntegrationRepo_Upsert_Call) RunAndReturn(run func(context.Context, *model.UserIntegration) error) *IntegrationRepo_Upsert_Call {
	_c.Call.Return(run)
	return _c
}

// NewIntegrationRepo creates a new instance of IntegrationRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIntegrationRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *IntegrationRepo {
	mock := &IntegrationRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
