// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	strava_usecase "github.com/nikpopkov/running-club/api/internal/usecase/strava_usecase"
	mock "github.com/stretchr/testify/mock"
)

// StravaClient is an autogenerated mock type for the stravaClient type
type StravaClient struct {
	mock.Mock
}

type StravaClient_Expecter struct {
	mock *mock.Mock
}

func (_m *StravaClient) EXPECT() *StravaClient_Expecter {
	return &StravaClient_Expecter{mock: &_m.Mock}
}

// ExchangeToken provides a mock function with given fields: ctx, code
func (_m *StravaClient) ExchangeToken(ctx context.Context, code string) (*strava_usecase.TokenExchange, error) {
	ret := _m.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for ExchangeToken")
	}

	var r0 *strava_usecase.TokenExchange
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*strava_usecase.TokenExchange, error)); ok {
		return rf(ctx, code)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *strava_usecase.TokenExchange); ok {
		r0 = rf(ctx, code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*strava_usecase.TokenExchange)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StravaClient_ExchangeToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExchangeToken'
type StravaClient_ExchangeToken_Call struct {
	*mock.Call
}

// ExchangeToken is a helper method to define mock.On call
//   - ctx context.Context
//   - code string
func (_e *StravaClient_Expecter) ExchangeToken(ctx interface{}, code interface{}) *StravaClient_ExchangeToken_Call {
	return &StravaClient_ExchangeToken_Call{Call: _e.mock.On("ExchangeToken", ctx, code)}
}

func (_c *StravaClient_ExchangeToken_Call) Run(run func(ctx context.Context, code string)) *StravaClient_ExchangeToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *StravaClient_ExchangeToken_Call) Return(_a0 *strava_usecase.TokenExchange, _a1 error) *StravaClient_ExchangeToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *StravaClient_ExchangeToken_Call) RunAndReturn(run func(context.Context, string) (*strava_usecase.TokenExchange, error)) *StravaClient_ExchangeToken_Call {
	_c.Call.Return(run)
	return _c
}

// GetActivityStreams provides a mock function with given fields: ctx, accessToken, activityID
func (_m *StravaClient) GetActivityStreams(ctx context.Context, accessToken string, activityID int64) ([]strava_usecase.ActivityStreamPayload, error) {
	ret := _m.Called(ctx, accessToken, activityID)

	if len(ret) == 0 {
		panic("no return value specified for GetActivityStreams")
	}

	var r0 []strava_usecase.ActivityStreamPayload
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64) ([]strava_usecase.ActivityStreamPayload, error)); ok {
		return rf(ctx, accessToken, activityID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int64) []strava_usecase.ActivityStreamPayload); ok {
		r0 = rf(ctx, accessToken, activityID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]strava_usecase.ActivityStreamPayload)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int64) error); ok {
		r1 = rf(ctx, accessToken, activityID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StravaClient_GetActivityStreams_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActivityStreams'
type StravaClient_GetActivityStreams_Call struct {
	*mock.Call
}

// GetActivityStreams is a helper method to define mock.On call
//   - ctx context.Context
//   - accessToken string
//   - activityID int64
func (_e *StravaClient_Expecter) GetActivityStreams(ctx interface{}, accessToken interface{}, activityID interface{}) *StravaClient_GetActivityStreams_Call {
	return &StravaClient_GetActivityStreams_Call{Call: _e.mock.On("GetActivityStreams", ctx, accessToken, activityID)}
}

func (_c *StravaClient_GetActivityStreams_Call) Run(run func(ctx context.Context, accessToken string, activityID int64)) *StravaClient_GetActivityStreams_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int64))
	})
	return _c
}

func (_c *StravaClient_GetActivityStreams_Call) Return(_a0 []strava_usecase.ActivityStreamPayload, _a1 error) *StravaClient_GetActivityStreams_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *StravaClient_GetActivityStreams_Call) RunAndReturn(run func(context.Context, string, int64) ([]strava_usecase.ActivityStreamPayload, error)) *StravaClient_GetActivityStreams_Call {
	_c.Call.Return(run)
	return _c
}

// GetAthlete provides a mock function with given fields: ctx, accessToken
func (_m *StravaClient) GetAthlete(ctx context.Context, accessToken string) (*strava_usecase.Athlete, error) {
	ret := _m.Called(ctx, accessToken)

	if len(ret) == 0 {
		panic("no return value specified for GetAthlete")
	}

	var r0 *strava_usecase.Athlete
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*strava_usecase.Athlete, error)); ok {
		return rf(ctx, accessToken)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *strava_usecase.Athlete); ok {
		r0 = rf(ctx, accessToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*strava_usecase.Athlete)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, accessToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StravaClient_GetAthlete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAthlete'
type StravaClient_GetAthlete_Call struct {
	*mock.Call
}

// GetAthlete is a helper method to define mock.On call
//   - ctx context.Context
//   - accessToken string
func (_e *StravaClient_Expecter) GetAthlete(ctx interface{}, accessToken interface{}) *StravaClient_GetAthlete_Call {
	return &StravaClient_GetAthlete_Call{Call: _e.mock.On("GetAthlete", ctx, accessToken)}
}

func (_c *StravaClient_GetAthlete_Call) Run(run func(ctx context.Context, accessToken string)) *StravaClient_GetAthlete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *StravaClient_GetAthlete_Call) Return(_a0 *strava_usecase.Athlete, _a1 error) *StravaClient_GetAthlete_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *StravaClient_GetAthlete_Call) RunAndReturn(run func(context.Context, string) (*strava_usecase.Athlete, error)) *StravaClient_GetAthlete_Call {
	_c.Call.Return(run)
	return _c
}

// ListActivities provides a mock function with given fields: ctx, accessToken, page, perPage
func (_m *StravaClient) ListActivities(ctx context.Context, accessToken string, page int, perPage int) ([]strava_usecase.ActivitySummary, error) {
	ret := _m.Called(ctx, accessToken, page, perPage)

	if len(ret) == 0 {
		panic("no return value specified for ListActivities")
	}

	var r0 []strava_usecase.ActivitySummary
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) ([]strava_usecase.ActivitySummary, error)); ok {
		return rf(ctx, accessToken, page, perPage)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) []strava_usecase.ActivitySummary); ok {
		r0 = rf(ctx, accessToken, page, perPage)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]strava_usecase.ActivitySummary)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) error); ok {
		r1 = rf(ctx, accessToken, page, perPage)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StravaClient_ListActivities_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListActivities'
type StravaClient_ListActivities_Call struct {
	*mock.Call
}

// ListActivities is a helper method to define mock.On call
//   - ctx context.Context
//   - accessToken string
//   - page int
//   - perPage int
func (_e *StravaClient_Expecter) ListActivities(ctx interface{}, accessToken interface{}, page interface{}, perPage interface{}) *StravaClient_ListActivities_Call {
	return &StravaClient_ListActivities_Call{Call: _e.mock.On("ListActivities", ctx, accessToken, page, perPage)}
}

func (_c *StravaClient_ListActivities_Call) Run(run func(ctx context.Context, accessToken string, page int, perPage int)) *StravaClient_ListActivities_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *StravaClient_ListActivities_Call) Return(_a0 []strava_usecase.ActivitySummary, _a1 error) *StravaClient_ListActivities_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *StravaClient_ListActivities_Call) RunAndReturn(run func(context.Context, string, int, int) ([]strava_usecase.ActivitySummary, error)) *StravaClient_ListActivities_Call {
	_c.Call.Return(run)
	return _c
}

// NewStravaClient creates a new instance of StravaClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStravaClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *StravaClient {
	mock := &StravaClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
