// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	uuid "github.com/google/uuid"
	model "github.com/nikpopkov/running-club/api/internal/domain/model"
	mock "github.com/stretchr/testify/mock"
)

// ActivityRepo is an autogenerated mock type for the activityRepo type
type ActivityRepo struct {
	mock.Mock
}

type ActivityRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *ActivityRepo) EXPECT() *ActivityRepo_Expecter {
	return &ActivityRepo_Expecter{mock: &_m.Mock}
}

// FindByUser provides a mock function with given fields: ctx, userID
func (_m *ActivityRepo) FindByUser(ctx context.Context, userID uuid.UUID) ([]*model.Activity, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindByUser")
	}

	var r0 []*model.Activity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*model.Activity, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*model.Activity); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Activity)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ActivityRepo_FindByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByUser'
type ActivityRepo_FindByUser_Call struct {
	*mock.Call
}

// FindByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *ActivityRepo_Expecter) FindByUser(ctx interface{}, userID interface{}) *ActivityRepo_FindByUser_Call {
	return &ActivityRepo_FindByUser_Call{Call: _e.mock.On("FindByUser", ctx, userID)}
}

func (_c *ActivityRepo_FindByUser_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *ActivityRepo_FindByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *ActivityRepo_FindByUser_Call) Return(_a0 []*model.Activity, _a1 error) *ActivityRepo_FindByUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ActivityRepo_FindByUser_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]*model.Activity, error)) *ActivityRepo_FindByUser_Call {
	_c.Call.Return(run)
	return _c
}

// FindMonthStats provides a mock function with given fields: ctx, userID
func (_m *ActivityRepo) FindMonthStats(ctx context.Context, userID uuid.UUID) ([]model.MonthStat, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindMonthStats")
	}

	var r0 []model.MonthStat
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]model.MonthStat, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []model.MonthStat); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.MonthStat)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ActivityRepo_FindMonthStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindMonthStats'
type ActivityRepo_FindMonthStats_Call struct {
	*mock.Call
}

// FindMonthStats is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *ActivityRepo_Expecter) FindMonthStats(ctx interface{}, userID interface{}) *ActivityRepo_FindMonthStats_Call {
	return &ActivityRepo_FindMonthStats_Call{Call: _e.mock.On("FindMonthStats", ctx, userID)}
}

func (_c *ActivityRepo_FindMonthStats_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *ActivityRepo_FindMonthStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *ActivityRepo_FindMonthStats_Call) Return(_a0 []model.MonthStat, _a1 error) *ActivityRepo_FindMonthStats_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ActivityRepo_FindMonthStats_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]model.MonthStat, error)) *ActivityRepo_FindMonthStats_Call {
	_c.Call.Return(run)
	return _c
}

// FindPRs provides a mock function with given fields: ctx, userID
func (_m *ActivityRepo) FindPRs(ctx context.Context, userID uuid.UUID) ([]*model.PR, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindPRs")
	}

	var r0 []*model.PR
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*model.PR, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*model.PR); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.PR)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ActivityRepo_FindPRs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindPRs'
type ActivityRepo_FindPRs_Call struct {
	*mock.Call
}

// FindPRs is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *ActivityRepo_Expecter) FindPRs(ctx interface{}, userID interface{}) *ActivityRepo_FindPRs_Call {
	return &ActivityRepo_FindPRs_Call{Call: _e.mock.On("FindPRs", ctx, userID)}
}

func (_c *ActivityRepo_FindPRs_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *ActivityRepo_FindPRs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *ActivityRepo_FindPRs_Call) Return(_a0 []*model.PR, _a1 error) *ActivityRepo_FindPRs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ActivityRepo_FindPRs_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]*model.PR, error)) *ActivityRepo_FindPRs_Call {
	_c.Call.Return(run)
	return _c
}

// FindRaces provides a mock function with given fields: ctx, userID
func (_m *ActivityRepo) FindRaces(ctx context.Context, userID uuid.UUID) ([]*model.Race, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindRaces")
	}

	var r0 []*model.Race
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*model.Race, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*model.Race); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Race)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ActivityRepo_FindRaces_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindRaces'
type ActivityRepo_FindRaces_Call struct {
	*mock.Call
}

// FindRaces is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *ActivityRepo_Expecter) FindRaces(ctx interface{}, userID interface{}) *ActivityRepo_FindRaces_Call {
	return &ActivityRepo_FindRaces_Call{Call: _e.mock.On("FindRaces", ctx, userID)}
}

func (_c *ActivityRepo_FindRaces_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *ActivityRepo_FindRaces_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *ActivityRepo_FindRaces_Call) Return(_a0 []*model.Race, _a1 error) *ActivityRepo_FindRaces_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ActivityRepo_FindRaces_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]*model.Race, error)) *ActivityRepo_FindRaces_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *ActivityRepo) GetByID(ctx context.Context, id uuid.UUID) (*model.Activity, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *model.Activity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.Activity, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.Activity); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Activity)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ActivityRepo_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type ActivityRepo_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *ActivityRepo_Expecter) GetByID(ctx interface{}, id interface{}) *ActivityRepo_GetByID_Call {
	return &ActivityRepo_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *ActivityRepo_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *ActivityRepo_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *ActivityRepo_GetByID_Call) Return(_a0 *model.Activity, _a1 error) *ActivityRepo_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ActivityRepo_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*model.Activity, error)) *ActivityRepo_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewActivityRepo creates a new instance of ActivityRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewActivityRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *ActivityRepo {
	mock := &ActivityRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
