// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	uuid "github.com/google/uuid"
	model "github.com/nikpopkov/running-club/api/internal/domain/model"
	mock "github.com/stretchr/testify/mock"
)

// ActivityStreamRepo is an autogenerated mock type for the activityStreamRepo type
type ActivityStreamRepo struct {
	mock.Mock
}

type ActivityStreamRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *ActivityStreamRepo) EXPECT() *ActivityStreamRepo_Expecter {
	return &ActivityStreamRepo_Expecter{mock: &_m.Mock}
}

// FindByActivityID provides a mock function with given fields: ctx, activityID
func (_m *ActivityStreamRepo) FindByActivityID(ctx context.Context, activityID uuid.UUID) ([]*model.ActivityStream, error) {
	ret := _m.Called(ctx, activityID)

	if len(ret) == 0 {
		panic("no return value specified for FindByActivityID")
	}

	var r0 []*model.ActivityStream
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*model.ActivityStream, error)); ok {
		return rf(ctx, activityID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*model.ActivityStream); ok {
		r0 = rf(ctx, activityID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.ActivityStream)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, activityID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ActivityStreamRepo_FindByActivityID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByActivityID'
type ActivityStreamRepo_FindByActivityID_Call struct {
	*mock.Call
}

// FindByActivityID is a helper method to define mock.On call
//   - ctx context.Context
//   - activityID uuid.UUID
func (_e *ActivityStreamRepo_Expecter) FindByActivityID(ctx interface{}, activityID interface{}) *ActivityStreamRepo_FindByActivityID_Call {
	return &ActivityStreamRepo_FindByActivityID_Call{Call: _e.mock.On("FindByActivityID", ctx, activityID)}
}

func (_c *ActivityStreamRepo_FindByActivityID_Call) Run(run func(ctx context.Context, activityID uuid.UUID)) *ActivityStreamRepo_FindByActivityID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *ActivityStreamRepo_FindByActivityID_Call) Return(_a0 []*model.ActivityStream, _a1 error) *ActivityStreamRepo_FindByActivityID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ActivityStreamRepo_FindByActivityID_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]*model.ActivityStream, error)) *ActivityStreamRepo_FindByActivityID_Call {
	_c.Call.Return(run)
	return _c
}

// NewActivityStreamRepo creates a new instance of ActivityStreamRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewActivityStreamRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *ActivityStreamRepo {
	mock := &ActivityStreamRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
