// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	uuid "github.com/google/uuid"
	model "github.com/nikpopkov/running-club/api/internal/domain/model"
	mock "github.com/stretchr/testify/mock"
)

// ClubRepo is an autogenerated mock type for the clubRepo type
type ClubRepo struct {
	mock.Mock
}

type ClubRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *ClubRepo) EXPECT() *ClubRepo_Expecter {
	return &ClubRepo_Expecter{mock: &_m.Mock}
}

// GetByCoachID provides a mock function with given fields: ctx, coachID
func (_m *ClubRepo) GetByCoachID(ctx context.Context, coachID uuid.UUID) (*model.Club, error) {
	ret := _m.Called(ctx, coachID)

	if len(ret) == 0 {
		panic("no return value specified for GetByCoachID")
	}

	var r0 *model.Club
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.Club, error)); ok {
		return rf(ctx, coachID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.Club); ok {
		r0 = rf(ctx, coachID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Club)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, coachID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClubRepo_GetByCoachID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByCoachID'
type ClubRepo_GetByCoachID_Call struct {
	*mock.Call
}

// GetByCoachID is a helper method to define mock.On call
//   - ctx context.Context
//   - coachID uuid.UUID
func (_e *ClubRepo_Expecter) GetByCoachID(ctx interface{}, coachID interface{}) *ClubRepo_GetByCoachID_Call {
	return &ClubRepo_GetByCoachID_Call{Call: _e.mock.On("GetByCoachID", ctx, coachID)}
}

func (_c *ClubRepo_GetByCoachID_Call) Run(run func(ctx context.Context, coachID uuid.UUID)) *ClubRepo_GetByCoachID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *ClubRepo_GetByCoachID_Call) Return(_a0 *model.Club, _a1 error) *ClubRepo_GetByCoachID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ClubRepo_GetByCoachID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*model.Club, error)) *ClubRepo_GetByCoachID_Call {
	_c.Call.Return(run)
	return _c
}

// NewClubRepo creates a new instance of ClubRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClubRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *ClubRepo {
	mock := &ClubRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
