// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	uuid "github.com/google/uuid"
	model "github.com/nikpopkov/running-club/api/internal/domain/model"
	mock "github.com/stretchr/testify/mock"
)

// WorkoutRepo is an autogenerated mock type for the workoutRepo type
type WorkoutRepo struct {
	mock.Mock
}

type WorkoutRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *WorkoutRepo) EXPECT() *WorkoutRepo_Expecter {
	return &WorkoutRepo_Expecter{mock: &_m.Mock}
}

// FindByCompletedActivity provides a mock function with given fields: ctx, activityID
func (_m *WorkoutRepo) FindByCompletedActivity(ctx context.Context, activityID uuid.UUID) (*model.Workout, error) {
	ret := _m.Called(ctx, activityID)

	if len(ret) == 0 {
		panic("no return value specified for FindByCompletedActivity")
	}

	var r0 *model.Workout
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.Workout, error)); ok {
		return rf(ctx, activityID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.Workout); ok {
		r0 = rf(ctx, activityID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Workout)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, activityID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WorkoutRepo_FindByCompletedActivity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByCompletedActivity'
type WorkoutRepo_FindByCompletedActivity_Call struct {
	*mock.Call
}

// FindByCompletedActivity is a helper method to define mock.On call
//   - ctx context.Context
//   - activityID uuid.UUID
func (_e *WorkoutRepo_Expecter) FindByCompletedActivity(ctx interface{}, activityID interface{}) *WorkoutRepo_FindByCompletedActivity_Call {
	return &WorkoutRepo_FindByCompletedActivity_Call{Call: _e.mock.On("FindByCompletedActivity", ctx, activityID)}
}

func (_c *WorkoutRepo_FindByCompletedActivity_Call) Run(run func(ctx context.Context, activityID uuid.UUID)) *WorkoutRepo_FindByCompletedActivity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *WorkoutRepo_FindByCompletedActivity_Call) Return(_a0 *model.Workout, _a1 error) *WorkoutRepo_FindByCompletedActivity_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *WorkoutRepo_FindByCompletedActivity_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*model.Workout, error)) *WorkoutRepo_FindByCompletedActivity_Call {
	_c.Call.Return(run)
	return _c
}

// FindByUser provides a mock function with given fields: ctx, userID
func (_m *WorkoutRepo) FindByUser(ctx context.Context, userID uuid.UUID) ([]*model.Workout, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindByUser")
	}

	var r0 []*model.Workout
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*model.Workout, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*model.Workout); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Workout)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WorkoutRepo_FindByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByUser'
type WorkoutRepo_FindByUser_Call struct {
	*mock.Call
}

// FindByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *WorkoutRepo_Expecter) FindByUser(ctx interface{}, userID interface{}) *WorkoutRepo_FindByUser_Call {
	return &WorkoutRepo_FindByUser_Call{Call: _e.mock.On("FindByUser", ctx, userID)}
}

func (_c *WorkoutRepo_FindByUser_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *WorkoutRepo_FindByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *WorkoutRepo_FindByUser_Call) Return(_a0 []*model.Workout, _a1 error) *WorkoutRepo_FindByUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *WorkoutRepo_FindByUser_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]*model.Workout, error)) *WorkoutRepo_FindByUser_Call {
	_c.Call.Return(run)
	return _c
}

// FindCompletedWithoutActivity provides a mock function with given fields: ctx, userID
func (_m *WorkoutRepo) FindCompletedWithoutActivity(ctx context.Context, userID uuid.UUID) ([]*model.Workout, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindCompletedWithoutActivity")
	}

	var r0 []*model.Workout
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*model.Workout, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*model.Workout); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Workout)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WorkoutRepo_FindCompletedWithoutActivity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindCompletedWithoutActivity'
type WorkoutRepo_FindCompletedWithoutActivity_Call struct {
	*mock.Call
}

// FindCompletedWithoutActivity is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *WorkoutRepo_Expecter) FindCompletedWithoutActivity(ctx interface{}, userID interface{}) *WorkoutRepo_FindCompletedWithoutActivity_Call {
	return &WorkoutRepo_FindCompletedWithoutActivity_Call{Call: _e.mock.On("FindCompletedWithoutActivity", ctx, userID)}
}

func (_c *WorkoutRepo_FindCompletedWithoutActivity_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *WorkoutRepo_FindCompletedWithoutActivity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *WorkoutRepo_FindCompletedWithoutActivity_Call) Return(_a0 []*model.Workout, _a1 error) *WorkoutRepo_FindCompletedWithoutActivity_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *WorkoutRepo_FindCompletedWithoutActivity_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]*model.Workout, error)) *WorkoutRepo_FindCompletedWithoutActivity_Call {
	_c.Call.Return(run)
	return _c
}

// NewWorkoutRepo creates a new instance of WorkoutRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWorkoutRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *WorkoutRepo {
	mock := &WorkoutRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
