// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	uuid "github.com/google/uuid"
	model "github.com/nikpopkov/running-club/api/internal/domain/model"
	mock "github.com/stretchr/testify/mock"
)

// WorkoutRepo is an autogenerated mock type for the workoutRepo type
type WorkoutRepo struct {
	mock.Mock
}

type WorkoutRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *WorkoutRepo) EXPECT() *WorkoutRepo_Expecter {
	return &WorkoutRepo_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, w
func (_m *WorkoutRepo) Create(ctx context.Context, w *model.Workout) error {
	ret := _m.Called(ctx, w)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Workout) error); ok {
		r0 = rf(ctx, w)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WorkoutRepo_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type WorkoutRepo_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - w *model.Workout
func (_e *WorkoutRepo_Expecter) Create(ctx interface{}, w interface{}) *WorkoutRepo_Create_Call {
	return &WorkoutRepo_Create_Call{Call: _e.mock.On("Create", ctx, w)}
}

func (_c *WorkoutRepo_Create_Call) Run(run func(ctx context.Context, w *model.Workout)) *WorkoutRepo_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Workout))
	})
	return _c
}

func (_c *WorkoutRepo_Create_Call) Return(_a0 error) *WorkoutRepo_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *WorkoutRepo_Create_Call) RunAndReturn(run func(context.Context, *model.Workout) error) *WorkoutRepo_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *WorkoutRepo) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WorkoutRepo_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type WorkoutRepo_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *WorkoutRepo_Expecter) Delete(ctx interface{}, id interface{}) *WorkoutRepo_Delete_Call {
	return &WorkoutRepo_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *WorkoutRepo_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *WorkoutRepo_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *WorkoutRepo_Delete_Call) Return(_a0 error) *WorkoutRepo_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *WorkoutRepo_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *WorkoutRepo_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindByUser provides a mock function with given fields: ctx, userID
func (_m *WorkoutRepo) FindByUser(ctx context.Context, userID uuid.UUID) ([]*model.Workout, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindByUser")
	}

	var r0 []*model.Workout
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*model.Workout, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*model.Workout); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Workout)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WorkoutRepo_FindByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByUser'
type WorkoutRepo_FindByUser_Call struct {
	*mock.Call
}

// FindByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *WorkoutRepo_Expecter) FindByUser(ctx interface{}, userID interface{}) *WorkoutRepo_FindByUser_Call {
	return &WorkoutRepo_FindByUser_Call{Call: _e.mock.On("FindByUser", ctx, userID)}
}

func (_c *WorkoutRepo_FindByUser_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *WorkoutRepo_FindByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *WorkoutRepo_FindByUser_Call) Return(_a0 []*model.Workout, _a1 error) *WorkoutRepo_FindByUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *WorkoutRepo_FindByUser_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]*model.Workout, error)) *WorkoutRepo_FindByUser_Call {
	_c.Call.Return(run)
	return _c
}

// FindByUserWeek provides a mock function with given fields: ctx, userID, week, kind
func (_m *WorkoutRepo) FindByUserWeek(ctx context.Context, userID uuid.UUID, week int, kind model.WorkoutKind) ([]*model.Workout, error) {
	ret := _m.Called(ctx, userID, week, kind)

	if len(ret) == 0 {
		panic("no return value specified for FindByUserWeek")
	}

	var r0 []*model.Workout
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, model.WorkoutKind) ([]*model.Workout, error)); ok {
		return rf(ctx, userID, week, kind)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, model.WorkoutKind) []*model.Workout); ok {
		r0 = rf(ctx, userID, week, kind)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Workout)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int, model.WorkoutKind) error); ok {
		r1 = rf(ctx, userID, week, kind)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WorkoutRepo_FindByUserWeek_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByUserWeek'
type WorkoutRepo_FindByUserWeek_Call struct {
	*mock.Call
}

// FindByUserWeek is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - week int
//   - kind model.WorkoutKind
func (_e *WorkoutRepo_Expecter) FindByUserWeek(ctx interface{}, userID interface{}, week interface{}, kind interface{}) *WorkoutRepo_FindByUserWeek_Call {
	return &WorkoutRepo_FindByUserWeek_Call{Call: _e.mock.On("FindByUserWeek", ctx, userID, week, kind)}
}

func (_c *WorkoutRepo_FindByUserWeek_Call) Run(run func(ctx context.Context, userID uuid.UUID, week int, kind model.WorkoutKind)) *WorkoutRepo_FindByUserWeek_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(int), args[3].(model.WorkoutKind))
	})
	return _c
}

func (_c *WorkoutRepo_FindByUserWeek_Call) Return(_a0 []*model.Workout, _a1 error) *WorkoutRepo_FindByUserWeek_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *WorkoutRepo_FindByUserWeek_Call) RunAndReturn(run func(context.Context, uuid.UUID, int, model.WorkoutKind) ([]*model.Workout, error)) *WorkoutRepo_FindByUserWeek_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *WorkoutRepo) GetByID(ctx context.Context, id uuid.UUID) (*model.Workout, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *model.Workout
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.Workout, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.Workout); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Workout)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WorkoutRepo_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type WorkoutRepo_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *WorkoutRepo_Expecter) GetByID(ctx interface{}, id interface{}) *WorkoutRepo_GetByID_Call {
	return &WorkoutRepo_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *WorkoutRepo_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *WorkoutRepo_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *WorkoutRepo_GetByID_Call) Return(_a0 *model.Workout, _a1 error) *WorkoutRepo_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *WorkoutRepo_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*model.Workout, error)) *WorkoutRepo_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, w
func (_m *WorkoutRepo) Update(ctx context.Context, w *model.Workout) error {
	ret := _m.Called(ctx, w)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Workout) error); ok {
		r0 = rf(ctx, w)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WorkoutRepo_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type WorkoutRepo_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - w *model.Workout
func (_e *WorkoutRepo_Expecter) Update(ctx interface{}, w interface{}) *WorkoutRepo_Update_Call {
	return &WorkoutRepo_Update_Call{Call: _e.mock.On("Update", ctx, w)}
}

func (_c *WorkoutRepo_Update_Call) Run(run func(ctx context.Context, w *model.Workout)) *WorkoutRepo_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Workout))
	})
	return _c
}

func (_c *WorkoutRepo_Update_Call) Return(_a0 error) *WorkoutRepo_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *WorkoutRepo_Update_Call) RunAndReturn(run func(context.Context, *model.Workout) error) *WorkoutRepo_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewWorkoutRepo creates a new instance of WorkoutRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWorkoutRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *WorkoutRepo {
	mock := &WorkoutRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
